version: "3"
services:
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - "simple-cdn"
  simple-cdn:
    image: simple-cdn:latest
    container_name: simple-cdn
    ports:
      - "3000:80"
